(add-to-list 'load-path "~/.emacs.d/core")

(require 'vars)
(require 'utils)
(require 'init-pkgs)
(require 'auto-modes)
(require 'hooks)
(require 'modeline)
(require 'key-bindings)
(require 'preferences)
